version: '3.1'

services:
  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proselyte
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./dbdata:/var/lib/mysql/